FROM nginx:latest
RUN mkdir -p /usr/share/nginx/images
COPY default.conf /etc/nginx/conf.d/default.conf
RUN apt-get update && apt-get install -y openssh-server iproute2
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i '/^#PermitRootLogin prohibit-password/c\PermitRootLogin yes' /etc/ssh/sshd_config
EXPOSE 22
CMD service ssh start && nginx -g 'daemon off;'